title: A. Lyashuk
email: hello.lyashuk@gmail.com
name: "Alexander Lyashuk"
description: >- # this means to ignore newlines until "baseurl:"
  MS in Computer Science - Data Mining.
  Technical Lead @Modelplace.AI.
repository: "lxdv/lxdv.github.io"
github_username: lxdv
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-feed

author:
  name   : "Alexander Lyashuk"
  avatar : "/assets/org/me.jpg"
  bio    : "Technical Lead @Modelplace.AI. MS in Computer Science."
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/lxdv/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lxdv"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://gitlab.com/lxdv" 
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/lyashuk"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/lyashuk"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue_term: "pathname"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
